### PR TITLE
Autodoc

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by nsheff** [comment]
looks nice!

**Comment by nsheff** [comment]
The class description is displayed twice.

**Comment by nsheff** [comment]
descriptions that span lines are concatenated without a space.

**Comment by nsheff** [comment]
return value documentation is not shown .

**Comment by nsheff** [comment]
it appears to be showing all inherited values. not sure we want to do that...

**Comment by vreuter** [comment]
> return value documentation is not shown .

localized to cases where the docstring is improperly formatted

**Pull request merged**
